# Generated by Django 6.0.3 on 2026-04-08 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_guest_show_serie_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promos', to='content.content'),
        ),
    ]
