# Generated by Django 6.0.3 on 2026-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_promo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
