# Generated by Django 6.0.3 on 2026-04-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_promo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='content.content')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_video', to='content.multimedia')),
            ],
        ),
    ]
