# Generated by Django 6.0.3 on 2026-04-02 10:39
import os
import string
import random
from pathlib import Path

from django.contrib.auth.hashers import make_password
from dotenv import load_dotenv
from django.db import migrations


def create_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    BASE_DIR = Path(__file__).resolve().parent.parent.parent
    env_path = BASE_DIR / '.env'
    load_dotenv(BASE_DIR / '.env')
    admin_email = os.getenv("ADMIN_EMAIL")
    admin_password = os.getenv("ADMIN_PASSWORD")

    if not admin_password:
        chars = string.ascii_letters + string.digits + "!@#$%^&*"
        admin_password = ''.join(random.choice(chars)for _ in range(16))
        with open (env_path,'a')as f:
            f.write(f"\nADMIN_PASSWORD={admin_password}\n")

        if not User.objects.filter(email=admin_email).exists():
            User.objects.create(
                email=admin_email,
                username="Admin",
                password=make_password(admin_password),
                is_staff=True,
                is_superuser=True,
                is_active=True,
                role=1
            )
            print(f"[v] Admin {admin_email} created successfully!")

class Migration(migrations.Migration):


    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin)
    ]
